---
version: '3'
services:
  klaw-core:
    image: klaw-core:latest
    environment:
      KLAW_CLUSTERAPI_ACCESS_BASE64_SECRET: dGhpcyBpcyBhIHNlY3JldCB0byBhY2Nlc3MgY2x1c3RlcmFwaQ==
      klaw.uiapi.servers: http://klaw-cluster-api:9343      
    volumes:
      - "klaw_data:/klaw"
    ports:
      - 9097:9097
    extra_hosts:
      - "moby:127.0.0.1"

  klaw-cluster-api:
    image: klaw-cluster-api:latest    
    environment:
      KLAW_CLUSTERAPI_ACCESS_BASE64_SECRET: dGhpcyBpcyBhIHNlY3JldCB0byBhY2Nlc3MgY2x1c3RlcmFwaQ==
    volumes:
      - "klaw_data:/klaw"
    extra_hosts:
      - "moby:127.0.0.1"
    ports:
      - 9343:9343
volumes:
  klaw_data:
    driver: local
